apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: pbtuxtxyh-nodejs 
  janus-idp.io/tekton: pbtuxtxyh-nodejs
  backstage.io/kubernetes-id: pbtuxtxyh-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: pbtuxtxyh-nodejs
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml